// Editorial import from the approved proposal; runtime uses the generated JSON.
const fs = require('node:fs');
const source = fs.readFileSync('docs/proposition_progression_vitae_v2.md', 'utf8');
const entries = [
['Brujah','brujah','Le prix du refus|Les voix qui se lèvent|Briser les chaînes|Un ordre nouveau|La cause vous survivra',
'Exigez la restitution d’un bien confisqué ou la levée d’une interdiction de chasse.|Réunissez des alliés autour d’une action précise : obtenir un accès, protéger un témoin ou faire retirer une sanction.|Coupez le levier d’un maître chanteur ou empêchez une querelle de faire échouer une opération commune.|Faites appliquer de nouvelles conditions de partage du sang malgré ceux qui profitent des anciennes.|Confiez une cause à ceux qui la porteront autrement que vous.'],
['Gangrel','gangrel','Un toit pour la Bête|La piste ouverte|La chasse renversée|Les chemins de la nuit|La terre en héritage',
'Obtenez l’accès à une friche surveillée ou rendez un abri compatible avec vos besoins nocturnes.|Conduisez des compagnons à travers un secteur surveillé ou négociez l’usage d’un terrain revendiqué.|Identifiez puis neutralisez ce qui rend un refuge dangereux, ou déjouez les moyens employés pour vous suivre.|Reliez des abris menacés par un itinéraire réellement praticable, malgré une surveillance active.|Donnez à un autre les moyens de vivre sur ce territoire sans dépendre de votre présence.'],
['Malkavien','malkavian','La fissure du masque|Ce que nul ne voulait voir|Le fil dans le labyrinthe|La vérité qui renverse|Les échos après vous',
'Confrontez des témoignages incompatibles ou donnez un sens vérifiable à un détail déjà établi en scène.|Réunissez les indices d’une tromperie et obtenez qu’un interlocuteur méfiant agisse sur cette base.|Reliez plusieurs faits épars ou démontez le procédé utilisé pour fausser vos perceptions.|Établissez une vérité assez solide pour déjouer un plan ou contredire un groupe qui cherche à l’étouffer.|Transmettez vos découvertes à quelqu’un qui pourra aussi les remettre en question.'],
['Nosferatu','nosferatu','Une oreille derrière le mur|Le poids du secret|Dans la toile ennemie|Aveugler les guetteurs|Les murmures demeurent',
'Gagnez la confiance d’un gardien réticent ou vérifiez un renseignement que son détenteur protège.|Établissez une preuve compromettante, ou faites réellement exécuter une concession négociée grâce à elle.|Accédez à un canal fermé ou soustrayez un informateur à ceux qui le surveillent.|Identifiez les relais d’une surveillance puis privez-les de leur efficacité, ou retournez leur coopération.|Confiez des sources et leurs moyens de protection sans conserver seul toutes les clés.'],
['Toreador','toreador','Entrer dans la lumière|Le prix de la muse|Sauver la dernière beauté|Le salon des immortels|L’œuvre vous échappe',
'Obtenez une commande refusée jusque-là ou l’admission dans un cercle fermé grâce à votre intervention.|Faites d’une création l’enjeu d’un accord, ou obtenez pour un artiste des moyens qu’on lui refusait.|Neutralisez une menace sur un atelier ou faites adopter une autre lecture d’une réputation contestée.|Rendez un lieu culturel opérationnel malgré ceux qui veulent l’empêcher, ou faites aboutir un projet disputé.|Laissez d’autres reprendre une création ou préserver un lieu selon leur propre sensibilité.'],
['Ventrue','ventrue','Le droit de réclamer|La parole fait loi|Une couronne éprouvée|Tenir la cour|Le trône après vous',
'Négociez un accès fiable à des proies compatibles ou faites accepter une responsabilité que l’on vous conteste.|Obtenez l’exécution d’un accord entre rivaux ou le contrôle réel d’une ressource disputée.|Ralliez un intermédiaire hostile, ou rétablissez la capacité d’un groupe à suivre des décisions contestées.|Faites fonctionner une organisation commune malgré des intérêts rivaux et une opposition active.|Préparez une relève qui puisse effectivement décider sans attendre chacun de vos ordres.'],
['Tremere','tremere','Les veines du savoir|Le cercle sous tension|Délier le sort|Contre le sang adverse|Le grimoire ouvert',
'Analysez une anomalie avec une méthode possédée ou obtenez un texte protégé puis démontrez son utilité.|Récupérez un composant défendu ou surmontez une contrainte inhabituelle pendant un rituel connu.|Levez un effet identifié ou reconstituez une méthode autorisée à partir d’éléments incomplets.|Déjouez une opération adverse ou rendez une protection efficace malgré ceux qui cherchent à l’empêcher.|Transmettez une méthode éprouvée ou rendez votre pratique indépendante d’une tutelle établie.'],
['Lasombra','lasombra','La main invisible|Nul maître au-dessus|Retourner la nuit|L’ombre tient le terrain|Le pouvoir sans laisse',
'Changez les conditions d’un accord défavorable ou gagnez le concours d’un intermédiaire qui connaît votre faiblesse.|Supprimez le levier d’une mise sous tutelle ou neutralisez un obstacle concret à votre projet.|Faites changer de camp un partenaire adverse ou remplacez un moyen essentiel perdu en cours d’opération.|Préservez une position conquise contre une riposte réelle, ou prenez l’ascendant sur un réseau rival.|Établissez des relais qui restent efficaces même lorsqu’ils refusent de vous obéir aveuglément.'],
['Tzimisce','tzimisce','Le seuil du Dragon|Façonner ce qui est sien|Reprendre possession|Le domaine consacré|Au-delà de la possession',
'Faites appliquer une hospitalité contestée ou adaptez un refuge à une contrainte concrète de votre condition.|Écartez une ingérence dans votre domaine, ou réalisez une transformation utile permise par vos pouvoirs.|Récupérez un domaine compromis ou surmontez les contraintes d’une transformation réellement complexe.|Obtenez un accord protégeant un lieu disputé ou achevez une transformation qui change son fonctionnement.|Transmettez un domaine ou poursuivez une métamorphose sans effacer l’autonomie des autres personnages.'],
['Giovanni / Hecata','giovanni','Ce que les morts réclament|La dette au-delà du souffle|Délier les ombres|L’accord des deux rives|Un héritage sans repos',
'Récupérez un objet funéraire disputé ou faites honorer une obligation laissée par un défunt.|Négociez un service réellement rendu par un esprit accessible, ou réglez un héritage qui ouvre une ressource.|Levez une emprise avec les moyens possédés, ou vérifiez une vérité que des intérêts familiaux dissimulent.|Faites fonctionner un arrangement entre héritiers et morts, ou établissez un dispositif patrimonial contesté.|Transmettez les moyens d’honorer des obligations qui ne s’arrêteront pas avec votre départ.'],
['Séthites / Ministère','setite','La première entrave tombe|Une autre allégeance|Le dogme fissuré|Le cercle affranchi|Vos disciples sans vous',
'Obtenez l’abandon effectif d’une règle défendue ou entrez dans un cercle fermé par une offre ciblée.|Détachez quelqu’un d’une emprise ou obtenez une adhésion qui change réellement ses décisions.|Retournez un relais d’influence ou démontrez une contradiction qui affaiblit une autorité établie.|Faites fonctionner un cercle malgré l’opposition de ceux qui veulent conserver leur emprise.|Laissez votre enseignement vivre chez ceux qui peuvent aussi retourner vos arguments contre vous.'],
['Banu Haqim','banu_haqim','La balance du sang|La sentence accomplie|Derrière les protections|Nul au-dessus du jugement|La justice après le juge',
'Vérifiez une accusation contestée ou faites réellement restituer ce qui a été pris.|Retrouvez une cible et accomplissez l’objectif de la mission, ou faites exécuter un arbitrage refusé.|Contournez la protection d’un coupable ou retirez le levier qui empêchait une réparation.|Obtenez une réparation malgré une protection organisée, y compris dans votre propre camp.|Établissez un arbitrage qui ne repose plus sur votre seule présence.'],
['Ravnos','ravnos','Passer entre les regards|La fausse piste|Le piège retourné|Les routes insaisissables|Un nom laissé derrière',
'Contournez un accès gardé par une ruse crédible ou gagnez un refuge auprès d’un hôte méfiant.|Faites perdre votre trace à un poursuivant ou remplacez un objet sous une surveillance effective.|Obtenez un bien défendu sans affronter directement ses gardiens, ou désorganisez une opération adverse.|Rendez un passage utilisable sous surveillance ou faites échouer une chasse en retournant ses moyens.|Transmettez une route sûre ou quittez une identité devenue une entrave, sans quitter le serveur.'],
['Salubri','salubri','Un abri pour la douleur|Délivrer sans posséder|La porte reste ouverte|Le sanctuaire tient|Le soin vous survivra',
'Mettez un bénéficiaire à l’abri malgré un obstacle ou obtenez pour lui une assistance refusée.|Restaurez une capacité par des moyens autorisés ou retirez un levier de dépendance dangereux.|Préservez un lieu d’accueil menacé ou déjouez les recherches visant une personne protégée.|Brisez l’exploitation organisée de vos dons ou maintenez un sanctuaire face à une offensive.|Donnez à d’autres les moyens d’aider sans dépendre indéfiniment de votre disponibilité.'],
['Gargouilles','gargoyles','Le gardien choisit|La pierre ne cède pas|Briser la main du maître|Un refuge pour les libres|Des ailes sans chaînes',
'Empêchez une intrusion établie ou obtenez l’exercice d’une liberté jusque-là refusée.|Préservez une cible réellement attaquée ou neutralisez un moyen concret de servitude.|Faites tenir une défense dont l’ennemi connaît la faille, ou retirez quelqu’un d’un dispositif de contrôle.|Défendez un refuge collectif contre une offensive ou obtenez une autonomie face à des adversaires organisés.|Formez une relève capable de choisir ses engagements plutôt que de reproduire votre servitude.'],
['Samedi','samedi','Franchir le dégoût|La peur a un prix|La place du revenant|Ceux que la tombe rassemble|Un nom au-delà du corps',
'Gagnez un accès refusé à cause de votre condition ou récupérez un corps placé hors de portée.|Conduisez une opération discrète malgré votre apparence, ou obtenez un résultat par un effroi réellement joué.|Neutralisez une exploitation des morts ou établissez une ressource dans un milieu qui vous excluait.|Préservez un refuge attaqué ou faites coopérer ceux qui ne vous traitaient que comme un instrument.|Transmettez une place reconnue qui ne dépende pas uniquement de votre utilité macabre.'],
['Filles de la Cacophonie','daughters_cacophony','Une voix franchit la porte|Le chant perce le silence|La dissonance révélatrice|La voix qui fait basculer|D’autres voix après vous',
'Obtenez une audience refusée ou faites aboutir une intervention vocale malgré une perturbation réelle.|Faites parvenir un message que l’on cherche à empêcher, ou désamorcez une hostilité par vos moyens autorisés.|Déjouez une manipulation par votre intervention ou sauvez une opération malgré une voix compromise.|Faites basculer une confrontation organisée ou établissez un cercle d’influence contre une opposition active.|Transmettez un répertoire ou construisez une œuvre où les autres voix gardent leur autonomie.'],
['Baali','baali','Les cendres du secret|Le prix du pacte|Dénouer l’emprise|Contre les maîtres cachés|La dette ultime',
'Récupérez une preuve qui vous expose ou gagnez un intermédiaire dans un cercle occulte fermé.|Menez une opération liée à un engagement établi ou déjouez l’enquête menaçant un complice.|Neutralisez le levier d’une dette occulte ou déjouez un adversaire qui connaît vos pratiques.|Démantelez un dispositif adverse ou obtenez une autonomie réelle face à une tutelle établie.|Résolvez le prix d’un engagement majeur sans inventer de pouvoir ou effacer ses conséquences.'],
];
const scales = {1:[3,2,1,1,0],2:[0,5,4,2,0],3:[0,0,8,6,0],4:[0,0,0,12,0],5:[0,0,0,0,0]};
const actions = [];
for (const [heading, clan, titleText, hintText] of entries) {
  const section = source.split(`### ${heading}\n`)[1].split('\n### ')[0];
  const rows = [...section.matchAll(/^\| ([1-5]) — \d+ pt[s]? \| (.+) \|$/gm)];
  if (rows.length !== 5) throw new Error(`Missing levels: ${clan}`);
  const validation = section.match(/Validation : (.+)/)?.[1] || 'Le résultat doit être effectif, face à un obstacle établi en jeu. Les pouvoirs employés doivent être possédés.';
  rows.forEach((row, index) => {
    const level = Number(row[1]);
    actions.push({id:`vitae_${clan}_${level}`, clan, category:'clan', name:titleText.split('|')[index],
      description:row[2],
      hints:[hintText.split('|')[index]], requirement:validation,
      minBp:level,maxBp:5,points:scales[level][level-1],scaling:Object.fromEntries(scales[level].map((n,i)=>[i+1,n]))});
  });
}
const general = [
['first_frenzy','unique','La Bête à votre porte','Affrontez pour la première fois une crise où la Bête menace une vie, une couverture ou un engagement.',[3,2,1,1],'Une faim pressante ou une provocation peut mettre un allié en danger. Jouez la crise jusqu’à sa résolution, par la résistance ou la perte de contrôle.'],
['vitae_first_dependence','unique','Le sang fait des chaînes','Établissez votre première dépendance de sang et donnez-lui une place réelle dans la nuit.',[3,2,1,1],'Créez une goule ou constituez un lien selon les règles du serveur, puis jouez une obligation issue de cette dépendance. Une gorgée isolée ne suffit pas.'],
['vitae_mortal_break','unique','Ce nom n’est plus le vôtre','Abandonnez irréversiblement une part importante de votre vie mortelle pour préserver votre existence vampirique.',[4,3,2,1],'Renoncez à une identité devenue dangereuse, à un accès précieux ou à une relation impossible à préserver. Une visite ou une déclaration de détachement ne suffit pas.'],
['vitae_first_hunt','unique','La première traque','Menez à terme votre première chasse autonome malgré un obstacle qui aurait pu vous démasquer.',[2,1],'Obtenez le sang recherché puis traitez un témoin, une surveillance ou une intrusion territoriale. Le repas sans incident n’est pas cette épreuve.'],
['vitae_hunting_source','general','Une veine dans la cité','Ouvrez une source de chasse réellement exploitable là où vos proies ou les maîtres des lieux vous fermaient le passage.',[3,2,1,1],'Négociez un droit de chasse contesté, gagnez un accès surveillé ou établissez une couverture adaptée à vos proies. Une victime de plus ne constitue pas une ressource.'],
['vitae_restore_source','general','Rouvrir les veines','Rendez au sang un chemin que la menace avait fermé.',[4,4,3,2],'Identifiez ce qui a compromis votre ressource de chasse, traitez cette cause et rétablissez un accès utilisable. Remplacer simplement un repas manqué ne suffit pas.'],
['vitae_masquerade','general','Recoudre le voile','Étouffez une menace crédible avant qu’elle ne déchire la Mascarade.',[5,5,4,3],'Récupérez une preuve compromettante, déjouez une enquête ou neutralisez le risque posé par un témoin. L’opposition doit être établie et le danger effectivement traité.'],
['vitae_autonomy','general','Briser la laisse','Arrachez une autonomie réelle à une emprise qui organisait votre existence ou celle d’un autre.',[6,6,5,4],'Supprimez un levier de chantage ou démantelez un dispositif de contrôle. Un lien surnaturel ne disparaît que par les moyens prévus par les règles.'],
['vitae_extraction','general','Soustraire une vie à la nuit','Ramenez un allié ou une ressource vivante hors d’un danger qui pouvait réellement l’emporter.',[6,6,6,5],'Préparez une sortie, déjouez des poursuivants ou franchissez une défense. L’extraction doit aboutir malgré une opposition ; accompagner quelqu’un à l’abri ne suffit pas.'],
['vitae_crisis','general','Revenir du bord des cendres','Surmontez une crise vampirique qui menace un objectif important.',[5,5,4,3],'Sauvez votre opération malgré la faim, la Bête, le feu ou une exposition. Un danger provoqué puis annulé pour obtenir des points ne compte pas.'],
['vitae_learning','general','Le savoir sous les sceaux','Obtenez un enseignement occulte que l’on ne livrait pas au premier venu.',[4,4,3,2],'Gagnez l’accès à un maître réticent ou à un savoir protégé et accomplissez l’apprentissage prévu par le serveur. Les points n’accordent aucun pouvoir supplémentaire.'],
['vitae_defense','general','Que le refuge demeure','Brisez une offensive organisée contre un refuge ou un réseau de chasse.',[8,8,8,6],'Identifiez les moyens de l’adversaire puis faites échouer son opération, par défense, négociation ou détournement. Une ronde sans incident n’est pas une victoire.'],
['vitae_resonance','resonance','Le goût d’une âme vive','Atteignez une source au sang chargé d’une émotion établie, au terme d’une chasse qui ne vous était pas acquise.',[2,1],'Identifiez rage, passion, mélancolie ou calme dans la fiction puis surmontez l’obstacle d’accès. Ne comptez pas la même acquisition à la fois comme chasse et résonance.'],
['vitae_dyscrasia','resonance','L’empreinte dans le sang','Exploitez une dyscrasie exceptionnelle reconnue par le MJ, après en avoir conquis l’accès.',[5,5,3,2],'Enquêtez sur une source déjà établie et remplissez les conditions de son exploitation. Déclarer une émotion extrême ne crée pas une dyscrasie.'],
];
for (const [id,category,name,description,values,hint] of general) actions.push({id,category,name,description,hints:[hint],requirement:'Un obstacle réel et un résultat obtenu doivent apparaître dans la scène. Un même accomplissement ne se rémunère pas sous plusieurs noms.',points:values[0],minBp:1,maxBp:values.length,scaling:Object.fromEntries(values.map((n,i)=>[i+1,n])),legacyCompletedIds:id==='vitae_first_dependence'?['first_ghoul','first_blood_bond']:[]});
const verbs = {Faire:'Faites',Obtenir:'Obtenez',Rassembler:'Rassemblez',Briser:'Brisez',Préserver:'Préservez',Transformer:'Transformez',Mettre:'Mettez',Résoudre:'Résolvez',Sécuriser:'Sécurisez',Établir:'Établissez',Conduire:'Conduisez',Récupérer:'Récupérez',Rompre:'Rompez',Ouvrir:'Ouvrez',Transmettre:'Transmettez',Rendre:'Rendez',Dévoiler:'Dévoilez',Reconstituer:'Reconstituez',Déjouer:'Déjouez',Découvrir:'Découvrez',Infiltrer:'Infiltrez',Soustraire:'Soustrayez',Démanteler:'Démantelez',Retourner:'Retournez',Gagner:'Gagnez',Sauver:'Sauvez',Créer:'Créez',Conclure:'Concluez',Placer:'Placez',Rallier:'Ralliez',Unifier:'Unifiez',Assurer:'Assurez',Maintenir:'Maintenez',Élucider:'Élucidez',Acquérir:'Acquérez',Réussir:'Réussissez',Neutraliser:'Neutralisez',Renverser:'Renversez',Écarter:'Écartez',Accomplir:'Accomplissez',Prendre:'Prenez',Construire:'Construisez',Surmonter:'Surmontez',Adapter:'Adaptez',Réaliser:'Réalisez',Reprendre:'Reprenez',Achever:'Achevez',Protéger:'Protégez',Entrer:'Entrez',Détacher:'Détachez',Mener:'Menez',Confondre:'Confondez',Appliquer:'Appliquez',Franchir:'Franchissez',Détourner:'Détournez',Désorganiser:'Désorganisez',Sortir:'Sortez',Restaurer:'Restaurez',Empêcher:'Empêchez',Libérer:'Libérez',Former:'Formez'};
for (const action of actions.filter(a => a.clan)) {
  action.description = action.description.split(';').map(part => part.trim()).map(part => {
    const word = part.split(' ')[0];
    const key = word[0].toUpperCase() + word.slice(1);
    return verbs[key] ? verbs[key] + part.slice(word.length) : part;
  }).join('. Ou ');
}
const firstBeast = actions.find(a => a.id === 'first_frenzy');
firstBeast.id = 'vitae_first_beast';
firstBeast.legacyCompletedIds = ['first_frenzy'];
const catalog = {version:2,thresholds:{1:30,2:60,3:120,4:250},aliases:{hecata:'giovanni',ministry:'setite',setites:'setite',assamites:'banu_haqim',assamite:'banu_haqim',malkavien:'malkavian',gargouilles:'gargoyles'},actions};
fs.writeFileSync('data/blood_actions.json',JSON.stringify(catalog,null,2)+'\n');
console.log(`${actions.length} actions written`);
